sudo: required
language: c++

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_script:

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ..
  - myExe

notifications:
  email: false
